name: Codetest
on:
  push:
    branches:    
      - '**'
jobs:
  codetest:
    name: Codetest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Cache Go's build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache build tools
        id: cachebuildtools
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/go/bin/golangci-lint
          key: ${{ runner.os }}-tools-gol1647
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install golangci-lint
        if: steps.cachebuildtools.outputs.cache-hit != 'true'
        env:
          GOLANGCI_LINT_VERSION: v1.64.7
        run: |
          sudo curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Get dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make get

      - name: Codetest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make codetest

      - name: Vulncheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make vulncheck
